# Hostname and path to root
baseurl = "/"

# Language code (RSS and multilingual sites)
languageCode = "en-us"
languageLang = "en"

title = "Esteban Sastre"
theme = "hugo-ink"

# Default number elements per page in pagination.
paginate = 5

# Code highlighting
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Google Analytics tracking ID
googleAnalytics = "UA-99848055-1"
disqusShortname = "ink-demo"


# Populate .Site.Params variable to use in templates
[params]
	subtitle = "Pretty much everything that crosses my mind, thoughts and ramblings"

	# Optional 64x64 avatar image.
	avatar = "wizard.png"

	# Content types to disable Disqus on.
	# disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/fr0gs/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
